In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import statsmodels.formula.api as smf
import statsmodels.api as sm

date: date of recording

number_sta: unique number of the station

pmer: sea level pressure (hpa)

dd: wind direction at 10m (rose of 360)

ff: wind force at 10m (m/s)

t: temperature under shelter (degre C)

u: humidity

rr3: rainfall in 3 hours (mm and 1/10)

pres: pressure at station altitude (hpa)

dd_sin: sin component of wind direction

dd_cos: cos component of wind direction

The objective is to predict if a rainy event will occur according to other quantities present in the dataset.

In [3]:
data = pd.read_csv("data/weather.csv")
data.head()

,date,numer_sta,Latitude,Longitude,Altitude,pmer,dd,ff,t,u,ssfrai,rr3,pres,dd_sin,dd_cos
0,2010-01-01 00:00:00,7510.0,44.830667,-0.691333,47.0,99050.0,230.0,9.8,9.6,81.0,0.0,0,98410.0,-0.766044,-0.642788
1,2010-01-01 03:00:00,7510.0,44.830667,-0.691333,47.0,99160.0,250.0,11.8,8.7,87.0,0.0,0,98520.0,-0.939693,-0.342020
2,2010-01-01 06:00:00,7510.0,44.830667,-0.691333,47.0,99570.0,290.0,5.1,7.6,91.0,0.0,0,98920.0,-0.939693,0.342020
3,2010-01-01 09:00:00,7510.0,44.830667,-0.691333,47.0,99990.0,310.0,5.7,6.8,92.0,0.0,0,99340.0,-0.766044,0.642788
4,2010-01-01 12:00:00,7510.0,44.830667,-0.691333,47.0,100350.0,310.0,6.2,6.6,82.0,0.0,0,99690.0,-0.766044,0.642788

In [5]:
data.rr3.value_counts(normalize=True)

0    0.981965
1    0.018035
Name: rr3, dtype: float64

### Some Notes :

1) Clear imbalance 98.2 / 1.2

2) Measures at time 00 should not be part because we want to predict rr3 which is rain in the last 3 hours